### ISSUE TITLE
Config changes

### ISSUE THREAD

**Issue by Tony-BigDataVisions** [ryansherby/RedfinScraper#2]
Can the base URLs in the rsc config be changed? Meaning, if we wanted to view _sold_ properties vs just _for sale_ properties, could we change the base url? I think it needs to be of the shape https://www.redfin.com/zipcode/<zip_code>/filter/include=sold-<some_number>mo

**Comment by ryansherby** [comment]
Yes, this could be done, but it would require some refactoring. Why don't you submit a pull request with your proposed idea, and I'll review it?

Things to consider:
- How would users select sold vs. for-sale (the default)?
- If sold is chosen, how would users select the filter? (Probably limit to 1/3/6 mo; no link for 1 wk)
- How would this alternate path be modeled within the larger scraping program? (Ideally you would want to minimize redundancy as much as possible)

**Comment by ryansherby** [comment]
Option has been added. See updated usage instructions.
