### ISSUE TITLE
Downloads partial data:

### ISSUE THREAD

**Issue by spillai13** [ryansherby/RedfinScraper#5]
Sample code block where RedfinScraper does not work:

```python
from redfin_scraper import RedfinScraper
scraper = RedfinScraper()

scraper.setup('zip_code_database.csv', False)
print(scraper.scrape(zip_codes=['78704']))
print(scraper.scrape(city_states=['Austin, TX']))
```

**Comment by ryansherby** [comment]
Unfortunately, the scraper is limited to locations where the local MLS has approved Redfin.com to publicly share posted housing data. Austin, TX is one example of a location where the local MLS has not granted their approval.
