### ISSUE TITLE
reddit API limit?  (building a stream)

### ISSUE THREAD

**Issue by woodcock-usna** [ryansherby/RedfinScraper#6]
the smallest time unit supported by this app is 1mo...is that a limit built into the reddit API?

for a class, I'm trying to find examples of real data coming in a stream;  so, it would be grand if I could grab lots of zip codes, but for only a short period of time (day, hour, ??).

**Comment by ryansherby** [comment]
This is a scraper for the real estate listing website Redfin.com

**Comment by woodcock-usna** [comment]
well, yea, I got that.  I was just wondering if it might be possible to call it on the regular and simulate a stream, but with real data.  if the time unit could be set to 1 hour (e.g.) that would totally do the trick.  just curious.

**Comment by ryansherby** [comment]
You would have to design your own call script to have it run every hour
