### ISSUE TITLE
 API Results Limited to 350 Entries Regardless of Time Span

### ISSUE THREAD

**Issue by banjavi** [ryansherby/RedfinScraper#7]
`
scraper = RedfinScraper()
    scraper.setup(zip_database_path, multiprocessing=False)
    zip_codes = ['85255']
    
    for zip_code in zip_codes:
            data = scraper.scrape(zip_codes=[zip_code], sold=True, sale_period='1yr') # change to 3yr
            data.to_csv(os.path.join(output_dir, f'scraped_data_{zip_code}.csv'), index=False)`

--
**Steps to Reproduce:**

1. Set up the scraper with a specific zip code.
2. Scrape data for a 1-year time span.
3. Observe the number of results (350 in my case).
4. Increase the time span to 3 years.
5. Scrape data again for the same zip code.
6. Observe the number of results (still 350).

--- 

Any insights or workarounds would be appreciated. Thank you!

**Comment by ryansherby** [comment]
Hello,
Unfortunately, Redfin caps the amount of data that can be pulled from a single area to 350 (please see: https://support.redfin.com/hc/en-us/articles/360016476931-Downloading-Data-)

The only workaround that could potentially solve this is allowing the user to manually manipulate the viewport dimensions (lat/lon) to select a subset of the total sold in that zip code. The difficulty with this is that it places the onus on the user to choose all the viewport dimension subsets within a zip code that would be sufficient to capture all the data in 350-max sections. The risk of duplicate records is also very high with this method.

I can consider adding this functionality, but it may be more "hack-y" than the average user would find desirable.

**Comment by banjavi** [comment]
Gotcha, thanks for looking into this Ryan! For my purposes I was able to merge a few different date subsets (1mo, 3mo, 1yr, etc.) and drop duplicates to get to the sample size I needed. Hope Redfin increases this limit in the future
